POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTc0MDU0OTA2fQ.SxwkWb-tDpTqrQJOgW3xcPU0xI3sBjlQJ86ZgVzWkCk

{
	"text": "text2",
	"title": "title2"
}
######

POST http://localhost:3000/posts/14
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTc0MDU0OTA2fQ.SxwkWb-tDpTqrQJOgW3xcPU0xI3sBjlQJ86ZgVzWkCk

{
	"text": "rereply"
}

##################


GET http://localhost:3000/posts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTc0MDU0OTA2fQ.SxwkWb-tDpTqrQJOgW3xcPU0xI3sBjlQJ86ZgVzWkCk

##################

GET http://localhost:3000/posts/8/replies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTc0MDU0OTA2fQ.SxwkWb-tDpTqrQJOgW3xcPU0xI3sBjlQJ86ZgVzWkCk

#####################

POST http://localhost:3000/posts/2/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTc0MDU0OTA2fQ.SxwkWb-tDpTqrQJOgW3xcPU0xI3sBjlQJ86ZgVzWkCk

{
	"like": true
}
#####################
POST http://localhost:3000/posts/1/unlike
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTc0MDU0OTA2fQ.SxwkWb-tDpTqrQJOgW3xcPU0xI3sBjlQJ86ZgVzWkCk

{
	"unlike": true
}
#####################
GET http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTc0MDU0OTA2fQ.SxwkWb-tDpTqrQJOgW3xcPU0xI3sBjlQJ86ZgVzWkCk
###############

GET http://localhost:3000/posts?lastId=100
