# gskim@google.com = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTU0Njc4NjU3NX0.q9vsx08wGGB8hBVOTbNfYZ2U-QpgSIiwPM2MIsJ_23k
POST http://localhost:3000/users/email
Content-Type: application/json

{
	"email": "gskim@gmail.com",
	"password": "password"
}

####################################

PUT http://localhost:3000/users/email
Content-Type: application/json

{
	"email": "gskim@gmail.com",
	"password": "password"
}

####################################

PUT http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTczODk0MjU0fQ.sXg7cbrfoaG6NmjCGjA-50U-gqt_Z8p1b2dmDOiK-rs
Content-Type: application/json

{
	"nickname": "닉네임",
	"birthYear": 1987,
	"birthMonth": 12,
	"birthDay": 25,
	"gender": "m"
}

######################


GET http://localhost:3000/test
Content-Type: application/json

####################################